version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.6-temurin
    environment:
      ZOO_MY_ID: 1
      JVMFLAGS: "-Xms64m -Xmx128m"
      ZOO_4LW_COMMANDS_WHITELIST: "srvr,ruok"
    volumes:
      - zookeeper_datalog:/datalog
      - zookeeper_data:/data
    healthcheck:
      test: ["CMD-SHELL", 'echo "ruok" | nc -w 2 -q 2 localhost 2181 | grep imok']
      interval: 5s
      retries: 5

  kafka:
    # It is used for kafka logs.dir - can't be randomly changed
    hostname: kafka
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "3032:3032"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:3032
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 49999
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq:0.22.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          security:
            default-group: admin
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8085:8080
    links:
      - kafka

  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.6:latest
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
      - zookeeper

  cmak2zk:
    image: ghcr.io/eshepelyuk/dckr/cmak2zk:latest
    restart: on-failure
    volumes:
      - "${PWD}/cmak2zk/clusters.yaml:/app/etc/clusters.yaml:ro"
    command:
      - 'zookeeper:2181'
      - '/app/etc/clusters.yaml'
    depends_on:
      - zookeeper

volumes:
  zookeeper_datalog:
  zookeeper_data:
  kafka_data:
